name: online-seminar
channels:
    - conda-forge
    - defaults
dependencies:
    - python>=3.7
    - pip
    - numpy
    - scipy
    - matplotlib
    - pandas
    - pytables
    - xarray
    - rockhound
    - jupyter
    - pip:
        - git+git://github.com/aguspesce/modelling_earth@master
